#!/bin/bash -e

# INSTALL PACKER ON UBUNTU/DEBIAN

# Dependencies for installing packer
sudo apt install curl gnupg2 software-properties-common

# Install packer
curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
sudo apt-get update && sudo apt install packer
